### ISSUE TITLE
Make Size Field Optional

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#180]
As we are hoping to gather size information, it is not always known if it is second/thirdhand information.  As forcing this information to be populated can cause incorrect information to be entered, it was suggested by NVADG to either make this field optional or to have an "unknown" option.  I think as it is on the top of the entry, just making this not required would be the sufficient/correct solution.

**Comment by AlexMountain** [comment]
Whoever picks this up should note that this will have widespread impact on how we display animal size in many places across the app as we've currently been operating with the assumption that this field will always be populated.  They will all need to be updated to make sure the UI still looks good when size is null.

**Comment by trevorskaggs** [comment]
Ah good point, might make more sense to do "Unknown" as an option to avoid that?

**Comment by AlexMountain** [comment]
IIRC we made size required so that we could provide more detailed information to the Dispatch workflow so the dispatcher and evac team can make better decisions on vehicle and cage sizes.  I'm not sure I like "Unknown" here because it changes the map display to be "2 Unknown Dogs, 2 Unknown Cats" instead of "2 Large Dogs, 2 Small Cats" and I don't think that the context conveys what is unknown here very appropriately.

I'm still of mind to force them to make their best guess and if they're wrong it's kind of a non issue but if we really want to remove it from being required I think null might be the better case in light of the above, with the necessary changes elsewhere on the site to make it still look good.

**Comment by AlexMountain** [comment]
I'm going to take back some of what I said above.  Assuming we want to keep the ability to bin animals on the Dispatch Map by species and size, then I think just adding an unknown size option let's us best handle this scenario on the map as we would just have 1 extra "unknown" bin for each species and I think that provides adequate context.
