### ISSUE TITLE
Add "Autocomplete" to Dropdown fields

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#286]
From a user:

```Here's a little piece of input. I'm entering animals, and when I get to the [dropdown] inquiry, if you type in no and tab, it sticks with unknown, which slows down workflow a lot. I don't know if that's something you control or not. You literally can't type the word no and then tab over. Same for confined and injured.```

**Comment by AlexMountain** [comment]
So dropdowns already had autocomplete... the filtering was just defaulting to be more generous since the word "Unknown" has "no" in it.  I made an update to the logic here to only filter based on the start of the word: https://github.com/trevorskaggs/shelterly/pull/281/commits/13fd432b16f3d4a4ea982fd046a4e7ebfccccaeb
