### ISSUE TITLE
Updates to Kennel Card

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#344]
Currently the Kennel Card is accessed via the "Printer" icon from the Animal Details Page.  There are potentially additional fields, but the current version is going to likely have some scaling issues when the Behavior/Medical/Description fields have big content.

Current Kennel Card:
[CurrentKennelCard.pdf](https://github.com/trevorskaggs/shelterly/files/7018868/CurrentKennelCard.pdf)

- [ ] Better resizing/fitting for animal image
- [ ] Better resizing/fitting to accommodate behavior/medical/description fields
- [ ] More intelligent generation of row in Service Table

**Comment by trevorskaggs** [comment]
Additional Animal Care Schedule (ACS)
- Delete Owner Phone Number
- Delete Service Request Date
- Add Fixed
- Add Space for write in of:
 i) Collar/Halter
 ii) Microchip
 iii) Neck Tag
 iv) Under Vet Care

- Modify Table Columns to show as:
Date Time AR#  Actions Comments"

**Comment by AlexMountain** [comment]
@trevorskaggs Can you please clarify these for me?

`Better resizing/fitting for animal image` - Can you explain what the issue is?  Do you have sample image files I can use to test with?

`More intelligent generation of row in Service Table` - Do you have an idea what this intelligent generation should be like?

`Add Space for write in` - Are these all yes/no write in answers?  Just trying to figure out exactly how much space they need.

`Date Time AR# Actions Comments` - is AR# a new column?

**Comment by trevorskaggs** [comment]
`Better resizing/fitting for animal image` - Im just worried about bigger ratio pictures causing the image to fall out of that little box.  The ones I have test so far all seem to be about the same ratio, so maybe its not a real problem to solve!

`More intelligent generation of row in Service Table` - This one is basically when the content above is bigger and causes multiple lines. Right now the form is generating N number of rows, but instead might need to generate N-2 to allow for the bigger content block at the top.

`Add Space for write in`:
 - Under Vet Care: Y/N
 - Microchip/Neck Tag/Collar: We will need something like _____________ for each item.

`Date Time AR# Actions Comments - is AR# a new column?` - Yup, so that we are tracking who is doing the work.  AR is Animal Rescuer.

**Comment by AlexMountain** [comment]
`More intelligent generation of row in Service Table` - Yeah I'm not really sure how we can make this intelligently dynamic without forcing a fixed height for the above fields and cutting off extremely long texts.  Even then changing the margins makes a huge difference when actually going to print.  I currently have it down 9 rows for 21 total for a moderately completely filled out card in my testing, but maybe it would be better to err on the side of more rows since worst case it just means a 2nd page?
