### ISSUE TITLE
Compress PDFs

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#513]
The minimal PDF size is currently coming down as 10.3 MB

**Comment by parksjr** [comment]
This was a simple change available via the core pdf library we are using, and file sizes are <1mb instead of 10mb, thats awesome! However, a noticeable lag now exists between user click and file download, and given the nature of the change, that is to be expected. I added a "spinner" to those buttons to help UX.

Note: I wanted to add the spinner to the original print icon buttons (on the details pages) but that change wasn't easy and started to blow up scope. A nice to have ticket should be filed.
