### ISSUE TITLE
Add Hotline ServiceRequest Map

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#78]
We need to have map that allows Hotline to view the list of current SRs.  I feel like we could re-use a lot of the Dispatch map code in this case.  Might be nice to tie this into the ServiceRequest search functionality.

Would need the ability to:
- [ ] Filter based on status
- [ ] Colorize dots based on status (Open: Red, Assigned: Yellow, Closed: Grey)

**Comment by AlexMountain** [comment]
This issue doesn't really clarify on what page(s) the map should go on... in my mind I'm thinking directly on the Hotline landing page, so that the user can evaluate the current state and use that information in choosing which hotline workflow to start.

Are those colors already used elsewhere in rescue or could we go: (Open: Green, Assigned: Yellow, Closed: Red)?

**Comment by trevorskaggs** [comment]
I'm hoping to see the list of SRs also using the same bounding box logic.  That being said, also would be useful to have the SR Details button exposed.  I'm good with modifying the colors.

**Comment by AlexMountain** [comment]
Definitely on bounding box logic!  I was also thinking about the SR Details buttons, and I'm currently leaning towards making it available in a popup when a user clicks the marker.  One additional thought/question:

What is the default SR status(s) we want to display?  Is it all SRs?  If so, would we anticipate a lot of clutter over time from closed SRs?  My gut is telling me start with Open + Assigned, and either make multiple toggles, one for each status, or some kind of status multi selector so that any status combo could be displayed.  Thoughts?

**Comment by trevorskaggs** [comment]
I would say Open could work as a simple version (we have this logic already on the search page), then allow for single status choices.
